/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedTimesheetsRouteImport } from './routes/_authenticated/timesheets'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedApplicantsRouteImport } from './routes/_authenticated/applicants'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite.'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments.index'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff.$staffId'
import { Route as AuthenticatedPatientsDocumentsRouteImport } from './routes/_authenticated/patients..documents'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedAssessmentsSkinRouteImport } from './routes/_authenticated/assessments.skin'
import { Route as AuthenticatedAssessmentsRnRouteImport } from './routes/_authenticated/assessments.rn'
import { Route as AuthenticatedAssessmentsParticipantRouteImport } from './routes/_authenticated/assessments.participant'
import { Route as AuthenticatedAssessmentsCaregiverRouteImport } from './routes/_authenticated/assessments.caregiver'
import { Route as AuthenticatedApplicantsApplicantIdRouteImport } from './routes/_authenticated/applicants.$applicantId'
import { Route as AuthenticatedPatientsPatientIdIndexRouteImport } from './routes/_authenticated/patients.$patientId.index'
import { Route as AuthenticatedPatientsPatientIdVisitsRouteImport } from './routes/_authenticated/patients.$patientId.visits'
import { Route as AuthenticatedPatientsPatientIdSkinRouteImport } from './routes/_authenticated/patients.$patientId.skin'
import { Route as AuthenticatedPatientsPatientIdRnAssessmentRouteImport } from './routes/_authenticated/patients.$patientId.rn-assessment'
import { Route as AuthenticatedPatientsPatientIdMedicationsRouteImport } from './routes/_authenticated/patients.$patientId.medications'
import { Route as AuthenticatedPatientsPatientIdFallRiskRouteImport } from './routes/_authenticated/patients.$patientId.fall-risk'
import { Route as AuthenticatedPatientsPatientIdDocumentsRouteImport } from './routes/_authenticated/patients.$patientId.documents'
import { Route as AuthenticatedPatientsPatientIdConsentRouteImport } from './routes/_authenticated/patients.$patientId.consent'
import { Route as AuthenticatedPatientsPatientIdCaregiverAssessmentRouteImport } from './routes/_authenticated/patients.$patientId.caregiver-assessment'
import { Route as AuthenticatedPatientsPatientIdCarePlanRouteImport } from './routes/_authenticated/patients.$patientId.care-plan'
import { Route as AuthenticatedPatientsPatientIdAssessmentsRouteImport } from './routes/_authenticated/patients.$patientId.assessments'
import { Route as AuthenticatedPatientsPatientIdAssessmentRouteImport } from './routes/_authenticated/patients.$patientId.assessment'
import { Route as AuthenticatedPatientsPatientIdAllergiesRouteImport } from './routes/_authenticated/patients.$patientId.allergies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimesheetsRoute = AuthenticatedTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicantsRoute = AuthenticatedApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite/',
  path: '/accept-invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedPatientsDocumentsRoute =
  AuthenticatedPatientsDocumentsRouteImport.update({
    id: '/patients/documents',
    path: '/patients/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentsSkinRoute =
  AuthenticatedAssessmentsSkinRouteImport.update({
    id: '/skin',
    path: '/skin',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedAssessmentsRnRoute =
  AuthenticatedAssessmentsRnRouteImport.update({
    id: '/rn',
    path: '/rn',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedAssessmentsParticipantRoute =
  AuthenticatedAssessmentsParticipantRouteImport.update({
    id: '/participant',
    path: '/participant',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedAssessmentsCaregiverRoute =
  AuthenticatedAssessmentsCaregiverRouteImport.update({
    id: '/caregiver',
    path: '/caregiver',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AuthenticatedApplicantsApplicantIdRoute =
  AuthenticatedApplicantsApplicantIdRouteImport.update({
    id: '/$applicantId',
    path: '/$applicantId',
    getParentRoute: () => AuthenticatedApplicantsRoute,
  } as any)
const AuthenticatedPatientsPatientIdIndexRoute =
  AuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdVisitsRoute =
  AuthenticatedPatientsPatientIdVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdSkinRoute =
  AuthenticatedPatientsPatientIdSkinRouteImport.update({
    id: '/skin',
    path: '/skin',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdRnAssessmentRoute =
  AuthenticatedPatientsPatientIdRnAssessmentRouteImport.update({
    id: '/rn-assessment',
    path: '/rn-assessment',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdMedicationsRoute =
  AuthenticatedPatientsPatientIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdFallRiskRoute =
  AuthenticatedPatientsPatientIdFallRiskRouteImport.update({
    id: '/fall-risk',
    path: '/fall-risk',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdDocumentsRoute =
  AuthenticatedPatientsPatientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdConsentRoute =
  AuthenticatedPatientsPatientIdConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdCaregiverAssessmentRoute =
  AuthenticatedPatientsPatientIdCaregiverAssessmentRouteImport.update({
    id: '/caregiver-assessment',
    path: '/caregiver-assessment',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdCarePlanRoute =
  AuthenticatedPatientsPatientIdCarePlanRouteImport.update({
    id: '/care-plan',
    path: '/care-plan',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdAssessmentsRoute =
  AuthenticatedPatientsPatientIdAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdAssessmentRoute =
  AuthenticatedPatientsPatientIdAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdAllergiesRoute =
  AuthenticatedPatientsPatientIdAllergiesRouteImport.update({
    id: '/allergies',
    path: '/allergies',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accept-invite/': typeof AcceptInviteRoute
  '/applicants': typeof AuthenticatedApplicantsRouteWithChildren
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/applicants/$applicantId': typeof AuthenticatedApplicantsApplicantIdRoute
  '/assessments/caregiver': typeof AuthenticatedAssessmentsCaregiverRoute
  '/assessments/participant': typeof AuthenticatedAssessmentsParticipantRoute
  '/assessments/rn': typeof AuthenticatedAssessmentsRnRoute
  '/assessments/skin': typeof AuthenticatedAssessmentsSkinRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/patients/documents': typeof AuthenticatedPatientsDocumentsRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/allergies': typeof AuthenticatedPatientsPatientIdAllergiesRoute
  '/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/patients/$patientId/assessments': typeof AuthenticatedPatientsPatientIdAssessmentsRoute
  '/patients/$patientId/care-plan': typeof AuthenticatedPatientsPatientIdCarePlanRoute
  '/patients/$patientId/caregiver-assessment': typeof AuthenticatedPatientsPatientIdCaregiverAssessmentRoute
  '/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/rn-assessment': typeof AuthenticatedPatientsPatientIdRnAssessmentRoute
  '/patients/$patientId/skin': typeof AuthenticatedPatientsPatientIdSkinRoute
  '/patients/$patientId/visits': typeof AuthenticatedPatientsPatientIdVisitsRoute
  '/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/applicants': typeof AuthenticatedApplicantsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/applicants/$applicantId': typeof AuthenticatedApplicantsApplicantIdRoute
  '/assessments/caregiver': typeof AuthenticatedAssessmentsCaregiverRoute
  '/assessments/participant': typeof AuthenticatedAssessmentsParticipantRoute
  '/assessments/rn': typeof AuthenticatedAssessmentsRnRoute
  '/assessments/skin': typeof AuthenticatedAssessmentsSkinRoute
  '/patients/documents': typeof AuthenticatedPatientsDocumentsRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/allergies': typeof AuthenticatedPatientsPatientIdAllergiesRoute
  '/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/patients/$patientId/assessments': typeof AuthenticatedPatientsPatientIdAssessmentsRoute
  '/patients/$patientId/care-plan': typeof AuthenticatedPatientsPatientIdCarePlanRoute
  '/patients/$patientId/caregiver-assessment': typeof AuthenticatedPatientsPatientIdCaregiverAssessmentRoute
  '/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/rn-assessment': typeof AuthenticatedPatientsPatientIdRnAssessmentRoute
  '/patients/$patientId/skin': typeof AuthenticatedPatientsPatientIdSkinRoute
  '/patients/$patientId/visits': typeof AuthenticatedPatientsPatientIdVisitsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/accept-invite/': typeof AcceptInviteRoute
  '/_authenticated/applicants': typeof AuthenticatedApplicantsRouteWithChildren
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/timesheets': typeof AuthenticatedTimesheetsRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/_authenticated/applicants/$applicantId': typeof AuthenticatedApplicantsApplicantIdRoute
  '/_authenticated/assessments/caregiver': typeof AuthenticatedAssessmentsCaregiverRoute
  '/_authenticated/assessments/participant': typeof AuthenticatedAssessmentsParticipantRoute
  '/_authenticated/assessments/rn': typeof AuthenticatedAssessmentsRnRoute
  '/_authenticated/assessments/skin': typeof AuthenticatedAssessmentsSkinRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/_authenticated/patients/documents': typeof AuthenticatedPatientsDocumentsRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/patients/$patientId/allergies': typeof AuthenticatedPatientsPatientIdAllergiesRoute
  '/_authenticated/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/_authenticated/patients/$patientId/assessments': typeof AuthenticatedPatientsPatientIdAssessmentsRoute
  '/_authenticated/patients/$patientId/care-plan': typeof AuthenticatedPatientsPatientIdCarePlanRoute
  '/_authenticated/patients/$patientId/caregiver-assessment': typeof AuthenticatedPatientsPatientIdCaregiverAssessmentRoute
  '/_authenticated/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/_authenticated/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/_authenticated/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/_authenticated/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/_authenticated/patients/$patientId/rn-assessment': typeof AuthenticatedPatientsPatientIdRnAssessmentRoute
  '/_authenticated/patients/$patientId/skin': typeof AuthenticatedPatientsPatientIdSkinRoute
  '/_authenticated/patients/$patientId/visits': typeof AuthenticatedPatientsPatientIdVisitsRoute
  '/_authenticated/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accept-invite/'
    | '/applicants'
    | '/assessments'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/timesheets'
    | '/visits'
    | '/applicants/$applicantId'
    | '/assessments/caregiver'
    | '/assessments/participant'
    | '/assessments/rn'
    | '/assessments/skin'
    | '/patients/$patientId'
    | '/patients/documents'
    | '/staff/$staffId'
    | '/assessments/'
    | '/patients/'
    | '/patients/$patientId/allergies'
    | '/patients/$patientId/assessment'
    | '/patients/$patientId/assessments'
    | '/patients/$patientId/care-plan'
    | '/patients/$patientId/caregiver-assessment'
    | '/patients/$patientId/consent'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/fall-risk'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/rn-assessment'
    | '/patients/$patientId/skin'
    | '/patients/$patientId/visits'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accept-invite'
    | '/applicants'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/timesheets'
    | '/visits'
    | '/applicants/$applicantId'
    | '/assessments/caregiver'
    | '/assessments/participant'
    | '/assessments/rn'
    | '/assessments/skin'
    | '/patients/documents'
    | '/staff/$staffId'
    | '/assessments'
    | '/patients'
    | '/patients/$patientId/allergies'
    | '/patients/$patientId/assessment'
    | '/patients/$patientId/assessments'
    | '/patients/$patientId/care-plan'
    | '/patients/$patientId/caregiver-assessment'
    | '/patients/$patientId/consent'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/fall-risk'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/rn-assessment'
    | '/patients/$patientId/skin'
    | '/patients/$patientId/visits'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/accept-invite/'
    | '/_authenticated/applicants'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/timesheets'
    | '/_authenticated/visits'
    | '/_authenticated/applicants/$applicantId'
    | '/_authenticated/assessments/caregiver'
    | '/_authenticated/assessments/participant'
    | '/_authenticated/assessments/rn'
    | '/_authenticated/assessments/skin'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/documents'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/assessments/'
    | '/_authenticated/patients/'
    | '/_authenticated/patients/$patientId/allergies'
    | '/_authenticated/patients/$patientId/assessment'
    | '/_authenticated/patients/$patientId/assessments'
    | '/_authenticated/patients/$patientId/care-plan'
    | '/_authenticated/patients/$patientId/caregiver-assessment'
    | '/_authenticated/patients/$patientId/consent'
    | '/_authenticated/patients/$patientId/documents'
    | '/_authenticated/patients/$patientId/fall-risk'
    | '/_authenticated/patients/$patientId/medications'
    | '/_authenticated/patients/$patientId/rn-assessment'
    | '/_authenticated/patients/$patientId/skin'
    | '/_authenticated/patients/$patientId/visits'
    | '/_authenticated/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timesheets': {
      id: '/_authenticated/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AuthenticatedTimesheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applicants': {
      id: '/_authenticated/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof AuthenticatedApplicantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/accept-invite/': {
      id: '/accept-invite/'
      path: '/accept-invite'
      fullPath: '/accept-invite/'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/patients/documents': {
      id: '/_authenticated/patients/documents'
      path: '/patients/documents'
      fullPath: '/patients/documents'
      preLoaderRoute: typeof AuthenticatedPatientsDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments/skin': {
      id: '/_authenticated/assessments/skin'
      path: '/skin'
      fullPath: '/assessments/skin'
      preLoaderRoute: typeof AuthenticatedAssessmentsSkinRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/assessments/rn': {
      id: '/_authenticated/assessments/rn'
      path: '/rn'
      fullPath: '/assessments/rn'
      preLoaderRoute: typeof AuthenticatedAssessmentsRnRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/assessments/participant': {
      id: '/_authenticated/assessments/participant'
      path: '/participant'
      fullPath: '/assessments/participant'
      preLoaderRoute: typeof AuthenticatedAssessmentsParticipantRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/assessments/caregiver': {
      id: '/_authenticated/assessments/caregiver'
      path: '/caregiver'
      fullPath: '/assessments/caregiver'
      preLoaderRoute: typeof AuthenticatedAssessmentsCaregiverRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_authenticated/applicants/$applicantId': {
      id: '/_authenticated/applicants/$applicantId'
      path: '/$applicantId'
      fullPath: '/applicants/$applicantId'
      preLoaderRoute: typeof AuthenticatedApplicantsApplicantIdRouteImport
      parentRoute: typeof AuthenticatedApplicantsRoute
    }
    '/_authenticated/patients/$patientId/': {
      id: '/_authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/visits': {
      id: '/_authenticated/patients/$patientId/visits'
      path: '/visits'
      fullPath: '/patients/$patientId/visits'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdVisitsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/skin': {
      id: '/_authenticated/patients/$patientId/skin'
      path: '/skin'
      fullPath: '/patients/$patientId/skin'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdSkinRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/rn-assessment': {
      id: '/_authenticated/patients/$patientId/rn-assessment'
      path: '/rn-assessment'
      fullPath: '/patients/$patientId/rn-assessment'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRnAssessmentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/medications': {
      id: '/_authenticated/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdMedicationsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/fall-risk': {
      id: '/_authenticated/patients/$patientId/fall-risk'
      path: '/fall-risk'
      fullPath: '/patients/$patientId/fall-risk'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdFallRiskRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/documents': {
      id: '/_authenticated/patients/$patientId/documents'
      path: '/documents'
      fullPath: '/patients/$patientId/documents'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/consent': {
      id: '/_authenticated/patients/$patientId/consent'
      path: '/consent'
      fullPath: '/patients/$patientId/consent'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdConsentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/caregiver-assessment': {
      id: '/_authenticated/patients/$patientId/caregiver-assessment'
      path: '/caregiver-assessment'
      fullPath: '/patients/$patientId/caregiver-assessment'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdCaregiverAssessmentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/care-plan': {
      id: '/_authenticated/patients/$patientId/care-plan'
      path: '/care-plan'
      fullPath: '/patients/$patientId/care-plan'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdCarePlanRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/assessments': {
      id: '/_authenticated/patients/$patientId/assessments'
      path: '/assessments'
      fullPath: '/patients/$patientId/assessments'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdAssessmentsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/assessment': {
      id: '/_authenticated/patients/$patientId/assessment'
      path: '/assessment'
      fullPath: '/patients/$patientId/assessment'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdAssessmentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/allergies': {
      id: '/_authenticated/patients/$patientId/allergies'
      path: '/allergies'
      fullPath: '/patients/$patientId/allergies'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdAllergiesRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
  }
}

interface AuthenticatedApplicantsRouteChildren {
  AuthenticatedApplicantsApplicantIdRoute: typeof AuthenticatedApplicantsApplicantIdRoute
}

const AuthenticatedApplicantsRouteChildren: AuthenticatedApplicantsRouteChildren =
  {
    AuthenticatedApplicantsApplicantIdRoute:
      AuthenticatedApplicantsApplicantIdRoute,
  }

const AuthenticatedApplicantsRouteWithChildren =
  AuthenticatedApplicantsRoute._addFileChildren(
    AuthenticatedApplicantsRouteChildren,
  )

interface AuthenticatedAssessmentsRouteChildren {
  AuthenticatedAssessmentsCaregiverRoute: typeof AuthenticatedAssessmentsCaregiverRoute
  AuthenticatedAssessmentsParticipantRoute: typeof AuthenticatedAssessmentsParticipantRoute
  AuthenticatedAssessmentsRnRoute: typeof AuthenticatedAssessmentsRnRoute
  AuthenticatedAssessmentsSkinRoute: typeof AuthenticatedAssessmentsSkinRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
}

const AuthenticatedAssessmentsRouteChildren: AuthenticatedAssessmentsRouteChildren =
  {
    AuthenticatedAssessmentsCaregiverRoute:
      AuthenticatedAssessmentsCaregiverRoute,
    AuthenticatedAssessmentsParticipantRoute:
      AuthenticatedAssessmentsParticipantRoute,
    AuthenticatedAssessmentsRnRoute: AuthenticatedAssessmentsRnRoute,
    AuthenticatedAssessmentsSkinRoute: AuthenticatedAssessmentsSkinRoute,
    AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  }

const AuthenticatedAssessmentsRouteWithChildren =
  AuthenticatedAssessmentsRoute._addFileChildren(
    AuthenticatedAssessmentsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedPatientsPatientIdRouteChildren {
  AuthenticatedPatientsPatientIdAllergiesRoute: typeof AuthenticatedPatientsPatientIdAllergiesRoute
  AuthenticatedPatientsPatientIdAssessmentRoute: typeof AuthenticatedPatientsPatientIdAssessmentRoute
  AuthenticatedPatientsPatientIdAssessmentsRoute: typeof AuthenticatedPatientsPatientIdAssessmentsRoute
  AuthenticatedPatientsPatientIdCarePlanRoute: typeof AuthenticatedPatientsPatientIdCarePlanRoute
  AuthenticatedPatientsPatientIdCaregiverAssessmentRoute: typeof AuthenticatedPatientsPatientIdCaregiverAssessmentRoute
  AuthenticatedPatientsPatientIdConsentRoute: typeof AuthenticatedPatientsPatientIdConsentRoute
  AuthenticatedPatientsPatientIdDocumentsRoute: typeof AuthenticatedPatientsPatientIdDocumentsRoute
  AuthenticatedPatientsPatientIdFallRiskRoute: typeof AuthenticatedPatientsPatientIdFallRiskRoute
  AuthenticatedPatientsPatientIdMedicationsRoute: typeof AuthenticatedPatientsPatientIdMedicationsRoute
  AuthenticatedPatientsPatientIdRnAssessmentRoute: typeof AuthenticatedPatientsPatientIdRnAssessmentRoute
  AuthenticatedPatientsPatientIdSkinRoute: typeof AuthenticatedPatientsPatientIdSkinRoute
  AuthenticatedPatientsPatientIdVisitsRoute: typeof AuthenticatedPatientsPatientIdVisitsRoute
  AuthenticatedPatientsPatientIdIndexRoute: typeof AuthenticatedPatientsPatientIdIndexRoute
}

const AuthenticatedPatientsPatientIdRouteChildren: AuthenticatedPatientsPatientIdRouteChildren =
  {
    AuthenticatedPatientsPatientIdAllergiesRoute:
      AuthenticatedPatientsPatientIdAllergiesRoute,
    AuthenticatedPatientsPatientIdAssessmentRoute:
      AuthenticatedPatientsPatientIdAssessmentRoute,
    AuthenticatedPatientsPatientIdAssessmentsRoute:
      AuthenticatedPatientsPatientIdAssessmentsRoute,
    AuthenticatedPatientsPatientIdCarePlanRoute:
      AuthenticatedPatientsPatientIdCarePlanRoute,
    AuthenticatedPatientsPatientIdCaregiverAssessmentRoute:
      AuthenticatedPatientsPatientIdCaregiverAssessmentRoute,
    AuthenticatedPatientsPatientIdConsentRoute:
      AuthenticatedPatientsPatientIdConsentRoute,
    AuthenticatedPatientsPatientIdDocumentsRoute:
      AuthenticatedPatientsPatientIdDocumentsRoute,
    AuthenticatedPatientsPatientIdFallRiskRoute:
      AuthenticatedPatientsPatientIdFallRiskRoute,
    AuthenticatedPatientsPatientIdMedicationsRoute:
      AuthenticatedPatientsPatientIdMedicationsRoute,
    AuthenticatedPatientsPatientIdRnAssessmentRoute:
      AuthenticatedPatientsPatientIdRnAssessmentRoute,
    AuthenticatedPatientsPatientIdSkinRoute:
      AuthenticatedPatientsPatientIdSkinRoute,
    AuthenticatedPatientsPatientIdVisitsRoute:
      AuthenticatedPatientsPatientIdVisitsRoute,
    AuthenticatedPatientsPatientIdIndexRoute:
      AuthenticatedPatientsPatientIdIndexRoute,
  }

const AuthenticatedPatientsPatientIdRouteWithChildren =
  AuthenticatedPatientsPatientIdRoute._addFileChildren(
    AuthenticatedPatientsPatientIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicantsRoute: typeof AuthenticatedApplicantsRouteWithChildren
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTimesheetsRoute: typeof AuthenticatedTimesheetsRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRouteWithChildren
  AuthenticatedPatientsDocumentsRoute: typeof AuthenticatedPatientsDocumentsRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicantsRoute: AuthenticatedApplicantsRouteWithChildren,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTimesheetsRoute: AuthenticatedTimesheetsRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedPatientsPatientIdRoute:
    AuthenticatedPatientsPatientIdRouteWithChildren,
  AuthenticatedPatientsDocumentsRoute: AuthenticatedPatientsDocumentsRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AcceptInviteRoute: AcceptInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
