/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedPatientsPatientIdIndexRouteImport } from './routes/_authenticated/patients.$patientId.index'
import { Route as AuthenticatedPatientsPatientIdFallRiskRouteImport } from './routes/_authenticated/patients.$patientId.fall-risk'
import { Route as AuthenticatedPatientsPatientIdConsentRouteImport } from './routes/_authenticated/patients.$patientId.consent'
import { Route as AuthenticatedPatientsPatientIdAssessmentRouteImport } from './routes/_authenticated/patients.$patientId.assessment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdIndexRoute =
  AuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdFallRiskRoute =
  AuthenticatedPatientsPatientIdFallRiskRouteImport.update({
    id: '/fall-risk',
    path: '/fall-risk',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdConsentRoute =
  AuthenticatedPatientsPatientIdConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdAssessmentRoute =
  AuthenticatedPatientsPatientIdAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/patients/$patientId/assessment': typeof AuthenticatedPatientsPatientIdAssessmentRoute
  '/_authenticated/patients/$patientId/consent': typeof AuthenticatedPatientsPatientIdConsentRoute
  '/_authenticated/patients/$patientId/fall-risk': typeof AuthenticatedPatientsPatientIdFallRiskRoute
  '/_authenticated/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients/$patientId'
    | '/patients/'
    | '/patients/$patientId/assessment'
    | '/patients/$patientId/consent'
    | '/patients/$patientId/fall-risk'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients'
    | '/patients/$patientId/assessment'
    | '/patients/$patientId/consent'
    | '/patients/$patientId/fall-risk'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/'
    | '/_authenticated/patients/$patientId/assessment'
    | '/_authenticated/patients/$patientId/consent'
    | '/_authenticated/patients/$patientId/fall-risk'
    | '/_authenticated/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId/': {
      id: '/_authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/fall-risk': {
      id: '/_authenticated/patients/$patientId/fall-risk'
      path: '/fall-risk'
      fullPath: '/patients/$patientId/fall-risk'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdFallRiskRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/consent': {
      id: '/_authenticated/patients/$patientId/consent'
      path: '/consent'
      fullPath: '/patients/$patientId/consent'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdConsentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/assessment': {
      id: '/_authenticated/patients/$patientId/assessment'
      path: '/assessment'
      fullPath: '/patients/$patientId/assessment'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdAssessmentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
  }
}

interface AuthenticatedPatientsPatientIdRouteChildren {
  AuthenticatedPatientsPatientIdAssessmentRoute: typeof AuthenticatedPatientsPatientIdAssessmentRoute
  AuthenticatedPatientsPatientIdConsentRoute: typeof AuthenticatedPatientsPatientIdConsentRoute
  AuthenticatedPatientsPatientIdFallRiskRoute: typeof AuthenticatedPatientsPatientIdFallRiskRoute
  AuthenticatedPatientsPatientIdIndexRoute: typeof AuthenticatedPatientsPatientIdIndexRoute
}

const AuthenticatedPatientsPatientIdRouteChildren: AuthenticatedPatientsPatientIdRouteChildren =
  {
    AuthenticatedPatientsPatientIdAssessmentRoute:
      AuthenticatedPatientsPatientIdAssessmentRoute,
    AuthenticatedPatientsPatientIdConsentRoute:
      AuthenticatedPatientsPatientIdConsentRoute,
    AuthenticatedPatientsPatientIdFallRiskRoute:
      AuthenticatedPatientsPatientIdFallRiskRoute,
    AuthenticatedPatientsPatientIdIndexRoute:
      AuthenticatedPatientsPatientIdIndexRoute,
  }

const AuthenticatedPatientsPatientIdRouteWithChildren =
  AuthenticatedPatientsPatientIdRoute._addFileChildren(
    AuthenticatedPatientsPatientIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRouteWithChildren
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPatientsPatientIdRoute:
    AuthenticatedPatientsPatientIdRouteWithChildren,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
